### ISSUE TITLE
Report about trying to compile surge locally

### ISSUE THREAD

**Issue by andywenk** [rule110-io/surge#102]
Hey there,

I tried to compile surge locally on my machine:

* MacOSX (MacBook Pro (13-inch, 2017, Two Thunderbolt 3 ports, 2,5 GHz Dual-Core **Intel Core i7**)
* development branch https://github.com/rule110-io/surge/commit/52e02ed2b2035390483022428a3c3f7c344eb5f8

The reason is, that the latest build downloadable is not running on any Intel Mac OSX. See also: https://github.com/rule110-io/surge/issues/82

First of all, I installed wails.

* Wails CLI v2.0.0-rc.1.1

That led to the fact, that I had to change the version in go.mod:

* https://github.com/rule110-io/surge/blob/development/go.mod#L16

After doing so, the warning was gone. Then I tried to compile the app but received the error:

```
Building target: darwin/amd64
-----------------------------
  - Generating bindings: Error:
main.go:20:12: pattern frontend/dist: no matching files found

exit status 1


ERROR:
main.go:20:12: pattern frontend/dist: no matching files found

exit status 1 
```

I simply changed the folder `frontend/src` to `frontend/dist`

After that I was able to build:

```
Building target: darwin/amd64
-----------------------------
  - Generating bindings: Done.
  - No Install command. Skipping.
  - No Build command. Skipping.
  - Compiling application: Done.
  - Packaging application: Done.
Built '[MY_HOME_FOLDER]/Documents/code/surge/build/bin/Surge.app/Contents/MacOS/Surge' in 58.369s.
```
I started the binary and it led to another error:

```
➜  MacOS git:(development) ✗ ./Surge
#---- WARNING ----
The `RGBA` option has been deprecated. Please use `BackgroundColour`.
```
I changed this in https://github.com/rule110-io/surge/blob/development/main.go#L89:

`BackgroundColour:  &options.RGBA{R: 33, G: 37, B: 43, A: 255},`

I then tried to start the application binary but it simply does nothing. 

**question**: where are the logs located to see what happens?

I then tried to start the dev environment:

```
➜  surge git:(development) ✗ wails dev
Wails CLI v2.0.0-rc.1.1

Executing: go mod tidy
Building frontend for development...
  - Generating bindings: Done.
  - No Install command. Skipping.
  - No Build command. Skipping.
Building application for development...
  - Generating bindings: Done.
  - Compiling application: Done.
  - Packaging application: Done.

watching: [MY_HOME_FOLDER]/Documents/code/surge
... many more watching: ...

Watching (sub)/directory: [MY_HOME_FOLDER]/Documents/code/surge
Using DevServer URL: http://localhost:34115
Using reload debounce setting of 100 milliseconds
INF | Serving assets from disk: [MY_HOME_FOLDER]/Documents/code/surge/frontend/dist


To develop in the browser and call your bound Go methods from Javascript, navigate to: http://localhost:34115
```

Unfortunately, the page is not accessible under http://localhost:34115.

**question:** any idea what is wrong? 

Happy to try it out further with some help.

**Comment by Deepfried-Chips** [comment]
frontend/src should be left as is, you need to go into the frontend folder and run `npm run build` to build the frontend, where it will create a dist folder

**Comment by MutsiMutsi** [comment]
Deepfried is right, also we've just published the newest version. If you still have any problems there let us know in a new ticket.
