### ISSUE TITLE
True Bittorrent with NKN?

### ISSUE THREAD

**Issue by lonnietc** [rule110-io/surge#107]
Hello,

I have just recently started working with NKN and have been looking over the SDK's, for which I am actually surprised that there is not C/C++ SDK as well.

None the less, I am interested in building a type of complete bittorrent, or at least integrating the NKN mining code into one in Golang such that when they applications running then the users would be mining tokens.

With this in mind, I am wondering how similar Surge is to bittorrent as when I tried to start it up on my Windows machine, it said that I needed NKN tokens before I could use it and I would have thought that running Surge would mine tokens and not require them.

Did I miss something here?
Thanks

**Comment by MutsiMutsi** [comment]
HI @lonnietc thanks for checking out surge, we simply utilize the free bandwidth available on the network surge does not contribute to the proof of relay conensus network and does not participate in any kind of block proposals.

**Comment by lonnietc** [comment]
Thanks for the clarification on this and I am investigating the NKN SDK's to see how to write up some applications, or integrate the NKN code into some existing applications so that they can contribute to the PoR or pass through specific nodes so that the node gets the rewards.

I have a small private testnet set up locally to play around with for these ideas.

Have a great day
