### ISSUE TITLE
Discord invite invalid

### ISSUE THREAD

**Issue by pimboli** [rule110-io/surge#112]
Hi,

seems that the discord invite link is invalid.
Can you please check and share new link?

Thanks

**Comment by WizardOfCodez** [comment]
Hey there!
Sure, it's https://discord.gg/3NEezy6c
Where did you find the discord link that is invalid so I can change it?

**Comment by pimboli** [comment]
Thanks!

here in the readme:
https://github.com/rule110-io/surge/blob/development/README.md

**Comment by WizardOfCodez** [comment]
Thanks! Changed it!
