### ISSUE TITLE
WailsV2 not availble

### ISSUE THREAD

**Issue by lonnietc** [rule110-io/surge#115]
**Describe the bug**
I grabbed the Wails repo to build WailsV2 which compiled but it does not have the "-p" flag need in the Surge "wails build -p"

**Desktop (please complete the following information):**
 - OS: Windows 11 (x64)

Is there a way to build Surge natively with Golang without using WailsV2?

**Comment by MutsiMutsi** [comment]
Sadly not out of the box, however there are very few dependencies between /backend/ and /frontend/ most of which are event based, it should be fairly straightfoward to only take the native golang /backend/ folder, remove the frontend and clean up main.go to build without wails. 

With regards to building with wails itself it's best to follow the getting started tutorial on their website if you still plan on giving that another go.

**Comment by lonnietc** [comment]
Hello, and Thanks for your response.

Maybe I can start by working through your basic build using WailsV2.

When I tried, I found that the "-p" flag was not recognized. Maybe I was somehow using V1 instead of V2.

Can you please tell me the process that you used to install and compile your WailsV2 from their sources and maybe I can replicate your steps.

I will try again with as I could have missed something else as well:

```
go install github.com/wailsapp/wails/v2/cmd/wails@latest
```

On a question, is the "-p" for the "-platform windows/amd64" which is what I am guessing.

```
wails build -p
```

When I do a "wails build --help" then only "-platform string" is the closest thing to a "-p" flag.

I just want to get the Windows (initially) version to build from your basic instructions and once that is successful then I can think about modifying the codebase towards my goal.

Thanks again and have a great day

**Comment by lonnietc** [comment]
Maybe if you could give me the steps that you used to make the surge-portable version (windows) then I could try to replicate then here.

Thanks

**Comment by WizardOfCodez** [comment]
Solved in Discord - Repo is working, problems could be solved by updating dev environment
