### ISSUE TITLE
Build fails on Linux

### ISSUE THREAD

**Issue by majjuss** [rule110-io/surge#117]
**Describe the bug**
When using "go build" in the extracted source folder, go starts downloading dependencies from various github adresses, but keeps failing at:
build github.com/wailsapp/wails/v2/internal/frontend/devserver: cannot load github.com/wailsapp/wails/v2/internal/frontend/devserver: no Go source files

**To Reproduce**
1. Download latest linux source (v1.1.1-beta)
2. extract
3. open folder in Terminal
4. execute "go build"

**Expected behavior**
expected it to find all referenced sources while building

**Desktop (please complete the following information):**
 - OS: Linux Mint 20.3 Cinnamon
 - go version go1.13.8 linux/amd64

**Comment by majjuss** [comment]
OK sorry I got it wrong... I managed to build it now after installing wails and so on, just overlooked it at the github start page of the project...
now I have the surge in the /build/bin directory, but it does nothing. It is set as executable, but does not even produce any output when run from the command line :( what am I missing now?!

**Comment by WizardOfCodez** [comment]
The instructions on github are incomplete. Before running `wails build`  you need to cd into your /frontend folder and run `npm install` as well as `npm run build` so you have an actual frontend wails can run - didn't have a chance yet to update the repo

/edit: updated
