### ISSUE TITLE
license: why restrictive license with "All Rights Reserved"

### ISSUE THREAD

**Issue by milahu** [rule110-io/surge#123]
the current license says

- All Rights Reserved
- no warranty, no liability

<details>
<summary>LICENSE</summary>

https://github.com/rule110-io/surge/blob/ceda9be013bdb1493fe8c3b2d9b19ea3f0125041/LICENSE#L1-L11

</details>

why not use a more permissive license? (MIT license, ...)

with the current license, i must rewrite from scratch to publish changes
with a permissive license, i can make public forks to publish changes

spoiler: you wont stop NSA with a restrictive license.
i bet they have already made a private fork, to add code for surveillance

**Comment by MutsiMutsi** [comment]
Hi @milahu thank you for your interest, I will discuss this with the team.

**Comment by MutsiMutsi** [comment]
License updated.
