### ISSUE TITLE
Add support for Linx

### ISSUE THREAD

**Issue by Nobody9512** [rule110-io/surge#127]
Hello, I am a Linux user and I find your project very interesting. Unfortunately, Surge is currently not available for Linux. Would it be possible to release a Linux-specific version? This would greatly benefit many users, especially those who prefer open-source operating systems. Are there any plans or timelines for Linux support?

I look forward to hearing your thoughts on this. Thank you!

**Comment by MutsiMutsi** [comment]
Would it be possible for you to build from source? I don't believe there is any reason for the latest version not to be able to be built and ran on Linux.
