### ISSUE TITLE
[Feature] Dynamic Window size

### ISSUE THREAD

**Issue by CrackDavid** [rule110-io/surge#13]
**Is your feature request related to a problem? Please describe.**
On some devices with scale ratios and small displays surge window is too big for the screen.

**Describe the solution you'd like**
Be free to change display window size, minimize and maximize

**Comment by zbruceli** [comment]
It also happens on lower resolution Windows machine too. Attached a screenshot
https://media.discordapp.net/attachments/785208535821844570/786400697917767680/Immagine_2020-12-10_021433.png

**Comment by vensauro** [comment]
This wails update will solve this too? (the window being bigger than the app)
![image](https://user-images.githubusercontent.com/41435789/101947815-d273b700-3bcf-11eb-969d-346454f5a26e.png)

**Comment by WizardOfCodez** [comment]
> This wails update will solve this too? (the window being bigger than the app)
> ![image](https://user-images.githubusercontent.com/41435789/101947815-d273b700-3bcf-11eb-969d-346454f5a26e.png)

Yes it definitely will!
