### ISSUE TITLE
[Bug] Search field is not working on MacOS

### ISSUE THREAD

**Issue by CrackDavid** [rule110-io/surge#14]
**Describe the bug**
The "Search for remote files..." input does not return any results no matter what is typed. Issue only happens on MacOS.

**To Reproduce**
1. Type something into the search field
2. no results

**Expected behavior**
Remote files list should be filtered

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur

**Comment by WizardOfCodez** [comment]
Fixed on next release
