### ISSUE TITLE
[Bug] Install as specific user on windows

### ISSUE THREAD

**Issue by MutsiMutsi** [rule110-io/surge#15]
**Describe the bug**
When installing surge on windows, and choosing the option for a specific user, the default download location is odd: "\AppData\Local\Programs\Surge"

During installation the following error is produced:
![image](https://user-images.githubusercontent.com/25252600/101394835-5f192f00-38c9-11eb-8092-a57b4f620e3c.png)

**To Reproduce**
1. Run installer on windows
2. Choose a user instead of all users
3. Continue as normal

**Expected behavior**
Program files dir as default and no registry error.

**Desktop (please complete the following information):**
 - Win 10 pro

**Comment by WizardOfCodez** [comment]
Will be fixed in v0.2.1-beta
