### ISSUE TITLE
[Bug] 0 Seeders in Remote Files 

### ISSUE THREAD

**Issue by WizardOfCodez** [rule110-io/surge#16]
**Describe the bug**
The Remote Files list can show 0 seeders if the only seeder available deletes the file and stays online

**To Reproduce**
1. Seeder: Seed file
2. Seeder: Remove file
3. Leecher: Check file listing

**Expected behavior**
Should not be shown in the remote files list.

**Comment by MutsiMutsi** [comment]
fixed in 0.2.1-beta
