### ISSUE TITLE
Generic dependency on webkit not hardcoded

### ISSUE THREAD

**Issue by mahdi1234** [rule110-io/surge#20]
```
./surge-0.2.0-beta 
./surge-0.2.0-beta: error while loading shared libraries: libwebkit2gtk-4.0.so.37: cannot open shared object file: No such file or directory

```
My gentoo system has already
```
dev-qt/qtwebengine-5.15.1
dev-qt/qtwebkit-5.212.0_pre20200309-r1
```
Would be great for user to have a choice.

**Comment by WizardOfCodez** [comment]
Hey there and thanks for your issue!

I guess that is more related to the wails-framework (https://github.com/wailsapp/wails) we use. Let me check with the devs if there are ways to make this happen.

**Comment by leaanthony** [comment]
I don't really understand the question. The app will require the same version of libwebkit installed to that which it was compiled with, which on the majority of distros will already be installed. Looks like you just need to install the library?
