### ISSUE TITLE
[Feature] Loading indicator when adding large file

### ISSUE THREAD

**Issue by WizardOfCodez** [rule110-io/surge#31]
**Is your feature request related to a problem? Please describe.**
Currently when adding large files nothing happens at the beginning. After a while file appears in surge. That happens because secure hashing takes some time depending on the machine surge is run on.

**Describe the solution you'd like**
Raise a message when hashing starts, raise a message when hashing ended.

**Possible text**
Surge makes your file now ready for sharing. To make the process as safe as possible we're now creating a hash of the full file that makes it impossible to tamper with it. You can close this modal. We will inform you when everything is done and your file is ready for seeding.

**Comment by no112358** [comment]
Just add a new item to the "file transfers list" and add a rotating icon at the start of the line, just so we know stuff is happening,

Had the same "problem" today and I was left wondering if anything is even happening.

**Comment by MutsiMutsi** [comment]
Implemented async hashing job in next release
