### ISSUE TITLE
Search directly for a file hash

### ISSUE THREAD

**Issue by no112358** [rule110-io/surge#32]
I want to be able to put a hash number into the search and find the file that way.

I tried it with the current 0.2.0-beta and it doesn't work.

Also currently you cannot just copy a hash from the files you upload.

Simple as that.

**Comment by MutsiMutsi** [comment]
Hi @no112358, thanks for your interest and welcome to github!

Great idea!
We've implemented searching by file hash you can expect it in the next release 0.2.1-beta.

With regards to copying hash from your own local files view, we are considering multiple ways to expose more information of files at subsequent releases.

**Comment by no112358** [comment]
I kinda already knew you already done it, seems like an obvious thing, just wrote it just in case.

Hash copying is not really neccesary if you're bringing Magnet links in 0.2.1-beta?

**Comment by MutsiMutsi** [comment]
We hadn't done it yet, but fulfilled your request 😉.
Can't say when exactly magnet links will be out, we're focussing mostly on bug fixing for 0.2.1-beta.

**Comment by no112358** [comment]
great job can't wait to see the results 👍
