### ISSUE TITLE
Wrong Download folder Windows10

### ISSUE THREAD

**Issue by no112358** [rule110-io/surge#33]
Surge is downloading to: C:\Users\*user*\Downloads\surge_remote
The problem is my Downloads directory was moved accordingly to another folder on a different drive. All other programs respect that except Surge.

The expected behaviour would be that surge uses a dynamic folder "link" that Windows provides.

Desktop:
 - Windows 10 2h2h
 - Firefox 83
 - Surge 0.2.0-beta

**Comment by MutsiMutsi** [comment]
Thanks for reporting, we've fixed this and you can expect it included in the 0.2.1-beta.

**Comment by no112358** [comment]
Great!
