### ISSUE TITLE
Search doesn't find items in "file transfers"

### ISSUE THREAD

**Issue by no112358** [rule110-io/surge#34]
Search seems not to look for items you already downloaded / are sharing. Also items downloaded already don't appear in the "remote files" tab. I take it that's by design.

Would be nice to quickly find items in the "file transfers" tab via search.

**Comment by MutsiMutsi** [comment]
Agreed that it would be nice to have more features to manage your own files, this is definitely planned for subsequent feature releases!

**Comment by WizardOfCodez** [comment]
Implemented in 0.3.0
