### ISSUE TITLE
BUG downloading into negative %

### ISSUE THREAD

**Issue by no112358** [rule110-io/surge#44]
**Describe the bug**
The download was added and it keeps on increasing into the negative %. It jumps to zero here and there and downloads back to negative %

**Screenshots**
![surge minus](https://user-images.githubusercontent.com/75950250/102829705-fad98d80-43e7-11eb-95e7-59cbd0dde638.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Version 0.2.1 beta

**Comment by no112358** [comment]
-68% now, I wanna see what happens at -100 % :D

**Comment by no112358** [comment]
Surge crashed again, no panic report.

Since both these things never happened before, I'm gonna assume they are connected.

![surge minus](https://user-images.githubusercontent.com/75950250/102880703-0b235400-444c-11eb-828c-9902768ee253.png)

EDIT:
The download actually finished after this. hehe

**Comment by MutsiMutsi** [comment]
Good morning, once again thanks for reporting!

The script error is a dupe from https://github.com/rule110-io/surge/issues/37
The negative progress will be solved with the newest version when the architechtural improvements are merged.

**Comment by no112358** [comment]
> 
> 
> Good morning, once again thanks for reporting!
> 
> The script error is a dupe from #37
> The negative progress will be solved with the newest version when the architechtural improvements are merged.

ohh sorry I searched but still missed it.
