### ISSUE TITLE
Surge does not run on Ubuntu 20.04-LTS desktop

### ISSUE THREAD

**Issue by zbruceli** [rule110-io/surge#46]
**Describe the bug**
It seems surge need higher version of glibc 2.32 than Ubuntu 20.04-LTS (2.31)

./surge
./surge: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./surge)

./apt install libc6
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libc6 is already the newest version (2.31-0ubuntu9.1).
libc6 set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by WizardOfCodez** [comment]
I just updated the linux executable on our release page - could you please redownload the file and try again?

**Comment by zbruceli** [comment]
Tested the latest Linux executable on Ubuntu 20.04-LTS desktop and it works properly. Issue closed.
