### ISSUE TITLE
Only first download is appearing in the File Transfers page

### ISSUE THREAD

**Issue by Chewie9999** [rule110-io/surge#52]
**Describe the bug**
The first file I downloaded showed up in the File Transfers page without problems, together with status updates etc.
Subsequent downloads are not showing up, even though they are are downloading without problems, are are shown the "alarm" drop down.

**To Reproduce**
1. Pick a file
2. Click download
3. Go to "File Transfers" screen
4. Nothing has been added, but first successful download is still showing

**Expected behavior**
Each file should show in the "File Transfer" list

**Screenshots**
![surgedownloads](https://user-images.githubusercontent.com/6060283/104839483-58fb7280-58b9-11eb-9359-56981d88de13.png)

**Desktop (please complete the following information):**
 - OS: openSUSE Tumbleweed 20210110

**Additional context**
This is the first and only time I have run Surge so far.

**Comment by MutsiMutsi** [comment]
Thank you for reporting, this has never been produced before, can you reproduce, and please if possible provide the log files (you can find the logs under the settings page of surge)

**Comment by Chewie9999** [comment]
Hi,
I've just restarted surge to try again - i've lost the logs as it only seems to keep the last days-worth :(
Please see the screenshot, all my previous downloads are now showing up (I deleted the Retro Pinball one)
![surge-afterrestart](https://user-images.githubusercontent.com/6060283/104951634-d6f37280-59ba-11eb-9b92-7592d87350ba.png)
I have now selected 2 additional files to download, and they seem to be showing up no problem.
Maybe it just happens on "first run"?
I will try more testing.
