### ISSUE TITLE
program loads to blank screen

### ISSUE THREAD

**Issue by kattiest** [rule110-io/surge#75]
hello, I am running pop OS 21.04 and when I open surge, either via the file or terminal I get a black box https://imgur.com/a/BomvAPX I attempted to trouble shoot the issue via terminal however I dont see any output about gfx or display

**Comment by MutsiMutsi** [comment]
Hi @kattiest,

First and foremost thanks for giving surge a go!
I've no experience with this distro, do you have any experience with running a project from code rather than a pre-compiled binary?

If so I think we could find out what is the issue for your OS specifically more easily as code debugging info would be available in such case.

**Comment by kattiest** [comment]
yes I do, I can grab the code later and compile to see if I can see anything

**Comment by MutsiMutsi** [comment]
Awesome, if you need any assistance, do let me know or hit me up on telegram @mutsimutsi or discord im in the rule110 channel of the nkn discord: https://discord.gg/hrZvrVa

**Comment by leaanthony** [comment]
@kattiest - I'm also keen to hear your findings
@MutsiMutsi - Let me know if you need Wails support 👍

**Comment by kattiest** [comment]
I have been having slight issues installing go on pop but I will figure it out as soon as I can and get back to you, turns out there was a snap package instead of using the source for go

**Comment by kattiest** [comment]
after compiling and playing with it for a bit it hasnt thrown up any errors past the original compiling for wails however still no gui, I will start making virtual machines and testing on various distros to see if its the same for all debian based distros or just pop

**Comment by leaanthony** [comment]
Thanks for the update.

**Comment by kattiest** [comment]
confirmed the same on a virtual machine of a ubuntu
