### ISSUE TITLE
Dead?

### ISSUE THREAD

**Issue by TheGalaxiaN** [rule110-io/surge#77]
**Describe the solution you'd like**
This was a promising project,is it officially dead?

**Comment by MutsiMutsi** [comment]
Hi @TheGalaxiaN thank you for your interest in our project!
We are looking to release a completely new version, revisited from the core tech to the ui design, very soon.

**Comment by TheGalaxiaN** [comment]
Thank you for the reply and for the fast releases to mac and windows, will there be Linux binaries or self build only?

**Comment by WizardOfCodez** [comment]
There will be a linux release if wails will add linux support. At the current state it seems like linux is not far away but we had a lot of problems in the past so we can tell more about it in maybe a month or two.
PR in the wails repo: https://github.com/wailsapp/wails/pull/1089
