### ISSUE TITLE
makefile that might be useful for others

### ISSUE THREAD

**Issue by gedw99** [rule110-io/surge#84]
just a make file you can drop into root to make it easier for people to get going. 

```

# https://github.com/rule110-io/surge

print:

all: f-build b-build

dep-os:
	# wails cli. TODO. modify to correct version as needed
	go install github.com/wailsapp/wails/v2/cmd/wails@latest

f-build:
	cd frontend && npm install
	cd frontend && npm run build
f-server:
	cd frontend && npm serve


b-doctor:
	wails doctor
b-dev:
	wails dev
b-serve:
	wails serve
b-build:
	wails build
b-dist:
	# mac in this case
	wails build -platform darwin/arm64 -clean


```

**Comment by gedw99** [comment]
also can add this

```
dep-os:
	# wails cli. TODO. modify to correct version as needed
	go install github.com/wailsapp/wails/v2/cmd/wails@latest
```

**Comment by gedw99** [comment]
Got it workng.

I had to create a new channel, as it would not let me upload to the official surge channel..
SO i created a new channel ("gedw99") and upload an image and video sample 



![Screenshot 2022-02-14 at 14 41 48](https://user-images.githubusercontent.com/53147028/153875144-8379069b-1b10-459a-9cd5-9362be3acc8a.png)

**Comment by MutsiMutsi** [comment]
Thank you for this! Could you turn this into a PR?
