### ISSUE TITLE
Is this project dead? 

### ISSUE THREAD

**Issue by Y0ngg4n** [rule110-io/surge#91]
No commits recently. Many open PRs. Is that project dead?

**Comment by MutsiMutsi** [comment]
Not quite, our development branches are also not publicly shown, we had to make changes that will allow for more wallet/blockchain features to ensure the application can keep running during times when there is network congestion for transactions and a fee needs to be added to ensure pubsub keeps working.

**Comment by Y0ngg4n** [comment]
ok thank you
